PLUGIN_SOURCE_FILES=slimer.c slimer_builtins.c
PLUGIN_OBJECT_FILES=slimer.o slimer_builtins.o
PLUGIN=slimer.so
EXTRA_ARGS=-fplugin-arg-slimer-numfuncs=20 -fplugin-arg-slimer-maxcalls=1000
EXTRA_OBJS=slimer_builtins.o

include ../make.inc
